server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NotesApp?createDatabaseIfNotExist=true
    username: root
    password: imanbello
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

resilience4j:
  circuitbreaker:
    instances:
      myServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
